name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarQube:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Cache SonarQube packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Install SonarQube Scanner
        run: |
          export SONAR_SCANNER_VERSION=4.6.2.2472
          export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION
          mkdir -p $SONAR_SCANNER_HOME
          curl -sSLo $SONAR_SCANNER_HOME/sonar-scanner-cli-$SONAR_SCANNER_VERSION.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION.zip
          unzip -q $SONAR_SCANNER_HOME/sonar-scanner-cli-$SONAR_SCANNER_VERSION.zip -d $HOME/.sonar/
          echo "$SONAR_SCANNER_HOME/bin" >> $GITHUB_PATH

      - name: Run SonarQube Scanner
        env:
          SONAR_HOST_URL: http://ec2-35-181-61-126.eu-west-3.compute.amazonaws.com
          SONAR_LOGIN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
          -Dsonar.projectKey=your_project_key \
          -Dsonar.organization=your_organization \
          -Dsonar.sources=. \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.login=$SONAR_LOGIN
